### ISSUE TITLE
Crashing when starting a run as Snecko from Downfall mod

### ISSUE THREAD

**Issue by dEVoRaTriX-LuX** [tetraminus/RiskOfRelics#12]
**Describe the bug**
Crash to desktop when playing as Snecko from Downfall

Here's the crash log:
Cause:
java.lang.NullPointerException
	at basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CreateCardImageSwitch$CreateCardImage.Prefix(CreateCardImageSwitch.java:24)
	at com.megacrit.cardcrawl.cards.AbstractCard.createCardImage(AbstractCard.java)
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:391)
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:322)
	at basemod.abstracts.CustomCard.<init>(CustomCard.java:94)
	at downfall.cards.OctoChoiceCard.<init>(OctoChoiceCard.java:58)
	at sneckomod.SneckoMod.findAWayToTriggerThisAtGameStart(SneckoMod.java:548)
	at sneckomod.SneckoMod.receivePostUpdate(SneckoMod.java:570)
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2414)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:897)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by dEVoRaTriX-LuX** [comment]
Additional crash log:
Clearing leaderboard font textures...
16:17:22.115 INFO demoMod.BetterSynergies> Reset all synergies.
16:17:22.326 INFO patches.RunStartEndPatches> Run Started
Using replacement play logic.
Obtaining source.
Prepping buffers.
????????0?????0?, ????????????
HermitMod | Loading Texture: downfallResources/images/vfx/beyondPortal.png
16:17:25.381 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CreateCardImageSwitch$CreateCardImage.Prefix(CreateCardImageSwitch.java:24) ~[?:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.createCardImage(AbstractCard.java) ~[?:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:391) ~[?:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:322) ~[?:?]
	at basemod.abstracts.CustomCard.<init>(CustomCard.java:94) ~[?:?]
	at downfall.cards.OctoChoiceCard.<init>(OctoChoiceCard.java:58) ~[?:?]
	at sneckomod.SneckoMod.findAWayToTriggerThisAtGameStart(SneckoMod.java:548) ~[?:?]
	at sneckomod.SneckoMod.receivePostUpdate(SneckoMod.java:570) ~[?:?]
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2414) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:897) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
Game crashed.

**Comment by tetraminus** [comment]
Risk of Relics doesn't seem to appear in the stacktrace anywhere. I'll take a look and keep this open, but maybe check with the Downfall devs as this seems to be a problem with the way their mod is generating card art.
