### ISSUE TITLE
Crash on continuing a run

### ISSUE THREAD

**Issue by Aweguy** [tetraminus/RiskOfRelics#15]
**Describe the bug**
Game crashes when i continue a run started before the updated version.

**To Reproduce**
1. Click to continue the run

**Expected behavior**
When it crashes it gives an error that says clearly it's this mod. Didn't happen before the update. As of writting, haven't tested new games.

**Additional context**
Here is the actual error the console gives me. 

java.lang.NullPointerException
	at riskOfRelics.util.CounterSavers$VengCounterSaver.onLoad(CounterSavers.java:37)
	at riskOfRelics.util.CounterSavers$VengCounterSaver.onLoad(CounterSavers.java:29)
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:42)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:108)
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1245)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:801)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by tetraminus** [comment]
are you playing with the artifact of vengeance enabled?

edit: Found the issue, and a fix will be out soon. right now loading pre update saves will crash.
