### ISSUE TITLE
Crash with Gesture of the Drowned & Pearlesence from Reliquary

### ISSUE THREAD

**Issue by ZoeyPageOfSpace** [tetraminus/RiskOfRelics#22]
**_I think Gesture of the Drowned is trying to cast a Pearlesence at the start of the game (Pearlesence copies the previous card played), resulting in my endless run... ending. I'll also report this to Reliquary to see if they can make a loophole for these situations._**

Cause:
java.lang.ClassCastException: automaton.cards.goodstatus.UnknownStatus cannot be cast to cards.colorless.CardPearlescence
	at cards.colorless.CardPearlescence.makeStatEquivalentCopy(CardPearlescence.java:148)
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.makeNewCard(MakeTempCardInHandAction.java:248)
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.addToHand(MakeTempCardInHandAction.java:98)
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.update(MakeTempCardInHandAction.java:79)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**_Might also be useful:_**

12:30:30.584 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame render method!
12:30:30.585 ERROR core.CardCrawlGame> Exception caught
java.lang.ClassCastException: automaton.cards.goodstatus.UnknownStatus cannot be cast to cards.colorless.CardPearlescence
	at cards.colorless.CardPearlescence.makeStatEquivalentCopy(CardPearlescence.java:148) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.makeNewCard(MakeTempCardInHandAction.java:248) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.addToHand(MakeTempCardInHandAction.java:98) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.update(MakeTempCardInHandAction.java:79) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
12:30:30.600 INFO core.CardCrawlGame> PAUSE()
12:30:30.600 INFO core.CardCrawlGame> Game shutting down...
12:30:30.600 INFO core.CardCrawlGame> Flushing saves to disk...
12:30:30.600 INFO core.CardCrawlGame> Shutting down controller handler...
12:30:30.600 INFO helpers.FileSaver> Save thread interrupted!
12:30:30.601 INFO helpers.FileSaver> Save thread will die now.
12:30:30.600 INFO core.CardCrawlGame> Shutting down publisher integrations...
12:30:30.604 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.

Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.1)
 - AIAdditions (1.4.0)
 - aspiration (1.9.5)
 - betterAltar (1.4)
 - Better_Animation (0.2.0)
 - betterNote (1.3)
 - betterStone (1.1)
 - betterSkull (1.2)
 - betterThird (1.5)
 - spiretalk (0.0.1)
 - Blade4All (0.2)
 - bloodstains (1.1.0)
 - BossyRelics (0.9.2)
 - bundlecore (4.0.4)
 - bundle_of_potions (2.3.5)
 - conspire (1.7.0)
 - timemazedefuse (1.0)
 - StSModEnergizedSpire (1.14.0)
 - GoodGameMod (0.1.2)
 - infinite_random (1.0)
 - MarkedMod (1.1.2)
 - OneHundredRelics (1.0.0)
 - PoorPeopleProblems (1.0.0)
 - relictweaks (1.0.0)
 - reliquary (0.5.2)
 - RiskOfRelics (2.1.11)
 - SuperPrismaticShard (1.1.0)
 - EvolutionMod (1.3.3)
 - TransformCurses (1.0)
 - RainbowJuice (0.1.0)
 - StackableRelics (1.3.6)
 - texturereplacer (1.1)
 - CardAugments (1.0.1)
 - downfall (5.0.2)
 - Better_Vampires (1.0.0)
 - bossedrelics (2.6.0)
 - ConstructionDeck (1.0)
 - ojb_easel (0.0.3)
 - ojb_mapmarks (0.0.1)
 - oceanmod (1.0.17)
 - quickrestart (2.0.5)
 - spirelocations (1.1.1)

**Comment by tetraminus** [comment]
at first glance this looks to be an issue with how pearlesence is trying to copy a card from downfall, this may be caused by gesture trying to play the card, but I think the crash may be something separate. I'll keep looking into it but I'd also check with the downfall team, as well as the reliquary team.

**Comment by ZoeyPageOfSpace** [comment]
oh! good point. I didn't catch "automaton.cards.goodstatus.UnknownStatus" - might also be a Bronze Idol issue.
