### ISSUE TITLE
TiS - Crash upon Bulwark's Ambry entry

### ISSUE THREAD

**Issue by DeffOS** [tetraminus/RiskOfRelics#41]
**Describe the bug**
Crash relates to Together in Spire (TiS) Multiplayer mod.
Generally it works fine with TiS but crashes whoever enter Bulwark's Ambry second or late
Reconnecting to run does not fixes it cause player still triggers Room's event
For first player entered crash doesnt appear

**To Reproduce**
1. On act 4 let one player pass Ambry
2. Go to it itself
3. Crash

**Crash log**
```
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - downfall (5.1.2)
 - spireTogether (6.4.11)
 - ReplayTheSpireMod (1.6.7)
 - GooglyMod (1.9.0)
 - TungstenRodVoiceMod (1.1.0)
 - RiskOfRelics (2.3.8)
 - thecursed (1.1.10)

Mods in stacktrace:
 - RiskOfRelics (2.3.8)
Cause:
java.lang.NullPointerException
    at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:275)
    at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:28)
    at riskOfRelics.rooms.AmbrySelectRoom.update(AmbrySelectRoom.java:43)
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
    at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
    at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by tetraminus** [comment]
After looking into this, it looks like the type of issue that would take major changes on either side to fix. I might look into it again, but compatibility jank is extremely time-consuming. I'll leave this open for now just in case I find a fix.
